name: Deploy prod

on:
    push:
        branches:
            - main
        tags: ['**']


jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Install Node.js
              uses: actions/setup-node@v4
              with:
                  node-version-file: 'package.json'
            - uses: pnpm/action-setup@v4
              name: Install pnpm
            - name: Install dependencies
              run: pnpm install
            - name: Lint scripts
              run: pnpm lint:js
            - name: Lint styles
              run: pnpm lint:css
            - name: Generate static site
              run: pnpm generate
            - uses: actions/upload-artifact@v4
              with:
                  name: built
                  path: app

    # This workflow contains a single job called "SFTP-Deploy-Action"
    SFTP-Deploy-Action:
        name: SFTP-Deploy-Action
        needs: build

        # The type of runner that the job will run on
        # (depends on server but usually this value is works)
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks
        # that will be executed as part of the job
        steps:

            - uses: actions/checkout@v4
            - uses: actions/download-artifact@v4
              with:
                  name: built
                  path: app
            - run: echo 'Successfully generate'
            - run: ls -lah app

            # This is a composite GitHub Action (Linux runner)
            # for deploying repository content to remote server
            - name: SFTP-Deploy-Action
              uses: milanmk/actions-file-deployer@master
              with:
                  remote-protocol: sftp

                  # Credentials for SFTP access to server using GitHub secrets
                  remote-host: ${{ secrets.FTP_HOST }}
                  remote-user: ${{ secrets.FTP_USER }}
                  remote-password: ${{ secrets.FTP_PASSWORD }}

                  # Path for specific folder on server for files deployment
                  remote-path: /home/juliegd/staging

                  # Port for SFTP access to server
                  remote-port: 221
